import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import TopNavGlass from "@/components/navbar/TopNavGlass";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Match Me",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const userId = session?.user?.id || null;
  const profileComplete = session?.user
    .profileComplete as boolean;
  return (
    <html lang="en">
      <body>
        <Providers
          profileComplete={profileComplete}
          userId={userId}
        >
          <TopNavGlass />
          <main className="container mx-auto">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}